# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Build Project
      run: |
        npm install --force
        npm run build --prod

    - name: List output files
      run: ls dist

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.cluster029.hosting.ovh.net
        username: jtksqfb
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/rc-website/
        server-dir: www/
        port: 21
        dangerous-clean-slate: true

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
